version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      target: builder
    container_name: fastapi-app
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=realnice.page
      - LETSENCRYPT_HOST=realnice.page
      - LETSENCRYPT_EMAIL=goo.denshlk@gmail.com
      - VIRTUAL_PORT=8000

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5433:5432'
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/my_init.sql

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      fastapi-app:
        condition: service_started

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=goo.denshlk@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  certs:
  html:
  vhost:
  acme:
